import Head from 'next/head';
import styles from '../styles/About.module.css';
import Image from 'next/image';
import { fetchEntry } from '../lib/contentful';

export default function About(props) {
  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>On Point Paving</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.headingContainer}>
          <h1>{props.pageContent.fields.heading}</h1>
        </div>
        <div className={styles.body}>
          <div className={styles.photo}>
            <Image
              alt="Freshly paved road with beautiful landscaping"
              src={`https:${props.pageContent.fields?.image?.fields.file.url}`}
              layout="fill"
              objectFit="cover"
            />
          </div>
          <p className={styles.mainText}>{props.pageContent.fields.textBody}</p>
        </div>
      </main>
    </div>
  );
}
export async function getStaticProps() {
  const pageContent = await fetchEntry('LTkXgdOxZMrSOcQkmxkoH');

  return {
    props: {
      pageContent,
    },
  };
}
