import Head from 'next/head';
import React, { useState, useEffect } from 'react';

import styles from '../styles/Contact.module.css';

export default function Contact() {
  const [formState, setFormState] = useState({
    name: '',
    phone: '',
    email: '',
    message: '',
  });

  const [honeypot, setHoneypot] = useState('');

  function handleSubmit(e) {
    e.preventDefault();
    //hidden input that only bots would be able to see and use
    if (honeypot) {
      console.log('bot detected');
      return;
    }
    const url =
      'https://script.google.com/macros/s/AKfycbyM9TlvuuHiC3-mg9WiVUuo4DzPzps6hCkNC1_3P5zOfGzSjQg76IB1E4qH3GNofGRS/exec';
    const data = formState;
    var xhr = new XMLHttpRequest();
    xhr.open('POST', url);
    // xhr.withCredentials = true;
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.onreadystatechange = function () {
      if (xhr.readyState === 4 && xhr.status === 200) {
        console.log('Form submitted');
      }
    };
    // url encode form data for sending as post data
    var encoded = Object.keys(data)
      .map(function (k) {
        return encodeURIComponent(k) + '=' + encodeURIComponent(data[k]);
      })
      .join('&');
    xhr.send(encoded);
  }

  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>On Point Paving</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.headingContainer}>
          <h1>CONTACT US</h1>
        </div>
        <p className={styles.mainText}>
          On Point Paving is standing by to assist with all your paving needs.
          Give us a call at 360-720-7606 or contact us below to receive a prompt
          quote or anwer to any questions. We look forward to helping you find
          the best solution for your project.
        </p>
        <div className={styles.formContainer}>
          <form className="gform" onSubmit={handleSubmit}>
            <div className={styles.inputContainer}>
              <label>
                NAME
                <input
                  type="text"
                  name="name"
                  value={formState.name}
                  onChange={(e) =>
                    setFormState({ ...formState, name: e.target.value })
                  }
                />
              </label>
            </div>
            <div className={styles.inputContainer}>
              <label>
                PHONE
                <input
                  type="tel"
                  name="phone"
                  value={formState.phone}
                  onChange={(e) =>
                    setFormState({ ...formState, phone: e.target.value })
                  }
                />
              </label>
            </div>
            <div className={styles.inputContainer}>
              <label>
                EMAIL
                <input
                  type="email"
                  name="email"
                  value={formState.email}
                  onChange={(e) =>
                    setFormState({ ...formState, email: e.target.value })
                  }
                />
              </label>
            </div>
            <div className={styles.inputContainer}>
              <label>
                MESSAGE
                <br />
                <textarea
                  name="message"
                  rows="10"
                  cols="30"
                  value={formState.message}
                  onChange={(e) =>
                    setFormState({ ...formState, message: e.target.value })
                  }
                />
              </label>
            </div>
            <div className={styles.honeypot}>
              <label>
                HONEYPOT
                <br />
                <input
                  name="honeypot"
                  type="text"
                  value={honeypot}
                  onChange={(e) => setHoneypot(e.target.value)}
                />
              </label>
            </div>
            <button type="submit">SUBMIT</button>
          </form>
        </div>
      </main>
    </div>
  );
}
