import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import photo from '../public/Oregon-City-3-scaled.jpg';
import Reviews from '../components/Reviews';

export default function Services() {
  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>On Point Paving</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.mainPhoto}>
          <Image
            alt="Freshly paved road with beautiful landscaping"
            src={photo}
            layout="fill"
            objectFit="cover"
            objectPosition="50% 42%"
            priority
          />
        </div>
        <div className={styles.tagline}>
          <h2>SERVICES</h2>
          <h1>ELITE PAVING SERVICE</h1>
        </div>
        <p className={styles.mainText}>
          On Point Paving is proud to offer high quality paving options for both
          commerical and residential projects. Our trusted experience and
          expertise will get the job done right at an affordable price. We are
          committed to providing exceptional paving solutions that will stand
          the test of time.
        </p>
      </main>
      <Reviews />
    </div>
  );
}
