import Head from 'next/head';
import Service from '../components/Service.js';
import styles from '../styles/Services.module.css';

import driveway from '../public/driveway.jpg';
import parkingLot from '../public/parkingLot.jpg';
import road from '../public/road.jpg';

export default function Services() {
  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>On Point Paving</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.headingContainer}>
          <h1>SERVICES</h1>
        </div>
        <p className={styles.mainText}>
          On Point Paving is proud to offer high quality paving options for both
          commerical and residential projects. Our trusted experience and
          expertise will get the job done right at an affordable price. We are
          committed to providing exceptional paving solutions that will stand
          the test of time.
        </p>
        <Service
          serviceName={'DRIVEWAY'}
          photo={driveway}
          description={
            'This section will cover the specifics for driveway paving.'
          }
        />
        <Service
          serviceName={'PARKING LOT'}
          photo={parkingLot}
          description={
            'This section will cover the specifics for parking lot paving.'
          }
        />
        <Service
          serviceName={'ROAD'}
          photo={road}
          description={'This section will cover the specifics for road paving.'}
        />
      </main>
    </div>
  );
}
