import Head from 'next/head';
import { fetchEntry, fetchServices } from '../lib/contentful';

import Service from '../components/Service.js';
import styles from '../styles/Services.module.css';

export default function Services(props) {
  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>On Point Paving</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.headingContainer}>
          <h1>{props?.pageContent.fields.heading}</h1>
        </div>
        <p className={styles.mainText}>{props?.pageContent.fields.textBody}</p>
        {props?.services.map((service, index) => {
          return (
            <Service
              serviceName={service.fields.serviceName}
              photo={`https:${service.fields?.image?.fields.file.url}`}
              description={service.fields.description}
              key={index}
            />
          );
        })}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const pageContent = await fetchEntry('1lrvROZ4p2Pd1KjCXiRExj');
  const servicesRes = await fetchServices();
  const services = await servicesRes.map((p) => {
    return p;
  });

  return {
    props: {
      pageContent,
      services,
    },
  };
}
